print("hello I am harsh I am going to make your introduction for you")
print("Answer the following questions which I will ask you")
name=input("what is your name")
print("hi",name)
age=int(input("What is your age"))
print("your age is ",age," okay")
city=input("In which city do you live?")
print(city," okay")
print("Making introduction..........")
print("Hello I am ",name," my age is ",age," I live in ",city)