a=str(input("Enter name of a fruit"))
b=input("Enter a name of a fruit")
c=input("Enter a name if a fruit")
d=input("Enter a name of a fruit")
e=input("Enter a name of a fruit")
f=input("Enter a name of a fruit")
g=input("Enter a name of a fruit")
print(list[a,b,c,d,e,f,g])